config/routes.rb
Localart::Application.routes.draw do
  
  root to: 'visitors#new'
  
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end
  resources :visitors, only: [:new, :create]
  
  get 'login'   => "user_sessions#new", :as => :login
  post 'logout'  => "user_sessions#destroy", :as => :logout

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
	has_no_table
	column :email, :string
	validates_presence_of :email
	validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

	def subscribe
		mailchimp = Gibbon::API.new
		result = mailchimp.lists.subscribe({
			:id => ENV['MAILCHIMP_LIST_ID'],
			:email => {:email => self.email},
			:double_optin => false,
			:update_existing => true,
			:send_welcome => true
		})
		Rails.logger.info("Subscribed #{self.email} to Mailchimp") if result
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

	private
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

app/controllers/artist_sessions_controller.rb
class ArtistSessionsController < ApplicationController

	# GET /sessions/new
  	def new
  		@artist = Artist.new
  	end

  # POST /sessions
	def create
	  if @artist = login(params[:email], params[:password])
	  	redirect_back_or_to(:artists, :notice => "Logged in !")
	  else
	  	flash.now[:alert] = "Login failed"
	  	render action: "new"
	  end
	end

	def destroy
	  logout
	  redirect_to root_url, :notice => "You have been logged out."
	end

	#private

	#def set_user
	#	@artist = login(params[:sessions][:email], params[:sessions][:password])
	#end

	#def sessions_params
	#	params.require(:artist).permit(:email, :password)
	#end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

	# GET /sessions/new
  	def new
  		@user = User.new
  	end

  # POST /sessions
	def create
	  if @user = login(params[:email], params[:password])
	  	redirect_back_or_to(:users, :notice => "Logged in !")
	  else
	  	flash.now[:alert] = "Login failed"
	  	render action: "new"
	  end
	end

	def destroy
	  logout
	  redirect_to root_url, :notice => "You have been logged out."
	end

	private

	#def set_user
	#	@artist = login(params[:sessions][:email], params[:sessions][:password])
	#end

	def sessions_params
		params.require(:user).permit(:email, :password)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @users = User.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @user = User.find(params[:id])
    @is_admin = current_user && current_user.id == @user.id
  end

  # GET /artists/new
  def new
    if current_user
      redirect_to root_path, :notice => "You are already registered"
    end
    @user = User.new
  end

  # GET /artists/1/edit
  def edit
    @user =  User.find(params[:id])
    if current_user.id != @user.id
      redirect_to @user
    end
  end

  # POST /artists
  # POST /artists.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Artist was successfully created."
    else
      render "new"
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, :notice => 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(login_path, :notice => 'User was successfully activated.')
    else
      not_authenticated
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  	def new
		@visitor = Visitor.new
		render 'visitors/new', :layout => 'special'
	end

	def create
		@visitor = Visitor.new(secure_params) 
		if @visitor.valid?
			@visitor.subscribe
			flash[:notice] = "Signed up #{@visitor.email} successfully." 
			redirect_to root_path
		else
			render :new
		end 
	end

	def show
	end

	private

	def secure_params 
		params.require(:visitor).permit(:email)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
      case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-block"
      else "alert #{level}"
      end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @artist.email %>
</p>

<p>



<% if (@is_admin) %>
  <%= link_to 'Edit', edit_artist_path(@artist) %>
<% end %>
<%= link_to 'Back', artists_path %>

app/views/layouts/_footer.html.erb
<div class="container">
    <div class="row" >
        <div class="col-sm-4">
        	<p class="text-center">Copyright Local Art 2014</p>
        </div>
        <div class="col-sm-4">
        	<p class="text-center">
        		Join us on : <br/><br/>
        	
        		<%= link_to image_tag('facebook-white.png', :class => "img-responsive", :style => "display:inline"), root_path %>
        		<%= link_to image_tag('tumblr-white.png', :class => "img-responsive", :style => "display:inline"), root_path %>
        		<%= link_to image_tag('twitter-white.png', :class => "img-responsive", :style => "display:inline"), root_path %>
        	</p>
        </div>
        <div class="col-sm-4" style="link-color: #eee;">
        		<p class="text-center">
        			Contact us :
        		</p>
        		<p class="text-center">
        			<a href="mailto:contact@local-art.fr">contact@local-art.fr</a>
        		</p>
        		<p class="text-center">
        			7, rue Oberkampf - 75011 Paris
        		</p>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3 column">
			<% flash.each do |name, msg| %>
			  <% if msg.is_a?(String) %>
			    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
			      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			      <%= content_tag :div, msg, :id => "flash_#{name}" %>
			    </div>
			  <% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top" >
  <%#<div class=="navbar-inner">%>
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag('logo.png', :class => "img-responsive"), root_path, class:'brand' %>
      </div>
      <div class="collapse navbar-collapse">
        <%= render 'layouts/navigation_links' %>
      </div>
    </div>
  <%#</div>%>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<ul class="nav navbar-nav">
	<li><%= link_to 'About', page_path('about') %></li>
    <% if current_user %>
		<li>
			<%= link_to 'LOGOUT', :logout, method: :post %>
		</li>
	<% else %>
		<li>
			<%= link_to 'REGISTER', new_user_path %>
		</li>
		<li>
			<%= link_to 'LOGIN', :login %>
		</li>
	<% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Local Art" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Local Art" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="hp">
      <div class="container">
        <!--<div class="content"> !-->
          <div class="row">
            <div class="col-lg-12 column">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        <!--</div>!-->
      </div>
    </main>
    <div class="footer">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Local Art" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Local Art" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrap-hp">
      <header>
        <%= render 'layouts/navigation' %>
      </header>
      <main role="main">
        <div class="container-fluid">
          <!--<div class="content"> !-->
            <div class="row">
              <div class="col-lg-12 text-center">
                <%= render 'layouts/messages' %>
                <%= yield %>
              </div>
              <div id="push"></div>
            </div>
          <!--</div>!-->
        </div>

      </main>
    </div>
    <div id="footer">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
	<div class="row" style="background-color: #333; color: #eee; padding-top:150px; padding-bottom:50px;">
		<div class="col-md-12">
			<h3>About Foobar Kadigan</h3>
			<p>He was born in Waikikamukau, New Zealand. He left New Zealand for England, excelled at the University of Mopery, and served in the Royal Loamshire Regiment. While in service, he invented the kanuten valve used in the processing of unobtainium for industrial use. He founded Acme Manufacturing, later acquired by the Advent Corporation, to commercialize the product. Mr. Kadigan is now retired and lives in Middlehampton where he raises Griadium frieda.</p>
			<p>His favorite quotation is:</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		</div>
	</div>
	<div class="row" style="background-color: #fdf4ef; padding-top:50px; padding-bottom:50px;">
		<div class="col-md-12">
			<h3>About Foobar Kadigan</h3>
			<p>He was born in Waikikamukau, New Zealand. He left New Zealand for England, excelled at the University of Mopery, and served in the Royal Loamshire Regiment. While in service, he invented the kanuten valve used in the processing of unobtainium for industrial use. He founded Acme Manufacturing, later acquired by the Advent Corporation, to commercialize the product. Mr. Kadigan is now retired and lives in Middlehampton where he raises Griadium frieda.</p>
			<p>His favorite quotation is:</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		</div>
	</div>

app/views/user_sessions/new.html.erb
<div class='jumbotron'>	
	<h1>Welcome back</h1>

	<!--<%= simple_form_for(:sessions, :url => 'sessions/create') do |f| %>
		<%= f.error_notification %>
		<%= f.input :email, as: :email %>
		<%= f.input :password, as: :password %>
		<%= f.button :submit, "Login", class: "btn btn-primary" %>
	<% end %>
	!-->
	<%= form_tag user_sessions_path, :method => :post do %>
		<div class='field'>
			<%= label_tag :email %><br />
			<%= text_field_tag :email %>
		</div>
		<div class='field'>
			<%= label_tag :password %><br />
			<%= text_field_tag :password %>
		</div>
		<div class='action'>
			<%= submit_tag "Login" %>
		</div>
	<% end %>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: {class: "form-default text-center"}) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, autofocus: true, label: "Your Name" %>
  <%= f.input :email, as: :email %>
  <%= f.input :password, as: :password %>
  <%= f.input :password_confirmation, as: :password %>

  <%= f.submit "Submit", :class => "btn-lg btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/users/index.html.erb
<h1>Listing artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_user_path %>

app/views/users/new.html.erb
<div class='row'>		
	<div class='col-sm-7 col-sm-offset-3'>
		<div class='jumbotron'>

			<h1>New artist</h1>

			<%= render 'form' %>

			<%= link_to 'Back', users_path %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @auser.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>



<% if (@is_admin) %>
  <%= link_to 'Edit', edit_user_path(@user) %>
<% end %>
<%= link_to 'Back', users_path %>

app/views/visitors/index.html.erb
<% content_for :title do %>Sign Up for Local Art<% end %>
<% content_for :description do %>Sign up to access Local Art beta release<% end %>
<div class="container">
	<div class="row" style="margin-top: 100px; margin-bottom: 300px;">
		<div class="col-sm-6 col-sm-offset-3 column hp-layer">
			<h1>Welcome to Local Art !</h1>
			<p>
				Parlez-en autours de vous pour remonter la file d'attente
			</p>
				
		</div>
	</div>
</div>

app/views/visitors/new.html.erb
<% content_for :title do %>Sign Up for Local Art<% end %>
<% content_for :description do %>Sign up to access Local Art beta release<% end %>
<div class="container">
	<div class="row" style="margin-top: 100px; margin-bottom: 20px;">
		<div class="col-sm-7 col-sm-offset-3 column hp-layer">
			<h1>Welcome to Local Art !</h1>
			<p>
				Sign up to receive a priority access for the BETA release.
			</p>
				<%= simple_form_for(@visitor, html: {class: "form-inline"}) do |f| %>
					<%= f.error_notification %>
					<%= f.input :email, label: false, :placeholder => 'Your email...' %>
					<%= f.submit "Go !", :class => "btn btn-primary" %>
				<% end %>
		</div>
	</div>
</div>